### ISSUE TITLE
byuu.org does not work on archive.org

### ISSUE THREAD

**Issue by ualaa1** [byuu/byuu.org#10]
I am interested in downloading older versions of BSNES, and I decided to do archive.org, as I recall Near saying that he put the page in there on a reddit thread long ago. I couldn't find the thread, but after doing some research, I noticed that Near has requested that byuu.org be in archive.org on another website (https://news.ycombinator.com/item?id=22654723) Maybe its a problem on their end again, and you might have to email them, like Near did?

**Comment by Screwtapello** [comment]
My recollection is than Near had to really twist archive.org's arm to get them to remove byuu.org, and I assume it would take equal or greater effort to put it back.

I'm not too worried about it, though - all the historic bsnes and higan releases should be available in the [bsnes-history-kit](https://gitlab.com/higan/bsnes-history-kit/-/tree/master/sources). Although it mostly focuses on source-archives rather than pre-compiled binaries, there's still a bunch of binary archives in there.

**Comment by ualaa1** [comment]
I'm pretty sure that post I linked shows that Near actually had to twist Archive.org's arm to put it in, not out. And if Near really did put archive.org out, why can't I find any mentions of that online, and why is archive.is still active then? I don't really know much about compiling then, so i guess I'll have to use archive.is then, even though I don't like its UI much.

**Comment by Screwtapello** [comment]
Near told me a bit of the story when he was handing me control of byuu.org, I don't know if he ever mentioned it publicly (although the fact that byuu.org is completely invisible on archive.org is a big clue something's up).

archive.is is apparently run by somebody who believes heavily in permanently archiving everything everywhere ever, to the point where they invest a lot of time and money getting around any attempt to block them from scraping a site.

**Comment by ualaa1** [comment]
I'm pretty sure even archive.is can be blocked with something like robots.txt
Near mentioned that he also had to remove some stuff in the link on the first post in order to get archive.is working
The fact that he could've just reblocked it but didn't makes me believe that the archive.org lock might be a bug
