### ISSUE TITLE
Redesign the bsnes and higan web pages

### ISSUE THREAD

**Issue by Screwtapello** [byuu/byuu.org#9]
Currently the webpages have the right basic information, but they could stand to be styled more nicely, and to make the information they have more accessible. For example, there's a lot of screenshots on the bsnes page, but they're way down below the fold, with no indication above the fold that that information is available.

Since we want to keep higan's website consistent with bsnes, this effectively depends on https://github.com/higan-emu/higan/issues/7

**Comment by near-san** [comment]
I've registered .dev domains for all three emulators, with a consistent look-and-feel for all three.

https://bsnes.dev, https://higan.dev, https://ares.dev

I'm still fleshing them out, but it should give a good general idea of what I'm going for.

I'd like to start the process of deprecating my old domain and letting the emulators stand on their own. I think this makes it more clear, at least for bsnes and higan, that they are community projects and not my personal project anymore. In the long-term, I want to redirect byuu.org at these .devs.

For the time being, I've given all three sites a consistent style. But I'd like to discuss this with other maintainers as to how we should handle this.

I'm fairly proud of my HTTP server and the CML/DML system that runs it. But I'm not sure how to expose it to you all for editing. I could add a small CMS login for folks here possibly.

Alternatively, I am willing to simply point the CNAMEs at GitHub and have the sites hosted here so everyone can edit them freely, but if we do that, I'd really want us to have a nice design for the sites first.

The websites really don't need to be much: something that makes the download links prominent, has some nice screenshots showing off the emulators and user interfaces, a few words about them, and that's about it really. User documentation on the GUIs would be nice, but given how rapidly I redesign the interfaces, it's ... probably not in the cards.

I'll volunteer to bump the version numbers on the site for each new release to take off that pain point, as I do think a version# on the site is important since we don't have an auto-updater.

I will maintain control of ares.dev for myself in any case. I'm going to try to start documenting more of the higan/ares internals there, and I want something convenient to me for that.

**Comment by Screwtapello** [comment]
After some discussion with Near, I've updated byuu.org/bsnes and byuu.org/higan to point at the .dev sites Near is maintaining, so this issue can be closed.
